# Generated by Django 3.1 on 2020-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='Фото'),
        ),
    ]
